// ? Стоимость инженера растёт с каждым использованием (I=2, II=3, III=4).
//   При доработке экономики пересмотреть: возможно, фиксированная стоимость + отдельная ветка апгрейдов.

export const CARD_DEFS = {
  engineer: {
    id: 'engineer',
    name: 'Инженер Узла',
    squadSize: 1,
    unitType: 'ground',
    armorClass: 'engineer',
    hp: 140,
    speed: 0.9,
    attackDamage: 0,
    buildingDamage: 0,
    attackCooldown: null,
    range: 0,
    targetTypes: [],
    canBlockGround: false,
    baseCost: 2,
    turnDelay: null,
    peelChance: 0,
    deployRules: {
      placementType: 'backline',
      allowedLanes: ['center'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
  },
  scout: {
    id: 'scout',
    name: 'Ищейка Барханов',
    squadSize: 2,
    cost: 2,
    unitType: 'ground',
    armorClass: 'light',
    hp: 220,
    speed: 1.6,
    attackDamage: 32,
    buildingDamage: 16,
    attackCooldown: 0.8,
    range: 0.8,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.15,
    peelChance: 0.65,
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
  },
  swordsman: {
    id: 'swordsman',
    name: 'Клинок Дома',
    squadSize: 3,
    cost: 2,
    unitType: 'ground',
    armorClass: 'medium',
    hp: 430,
    speed: 0.95,
    attackDamage: 45,
    buildingDamage: 32,
    attackCooldown: 1,
    range: 0.9,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.25,
    peelChance: 0.65,
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
  },
  assault: {
    id: 'assault',
    name: 'Башнелом',
    squadSize: 2,
    cost: 3,
    unitType: 'ground',
    armorClass: 'assault',
    hp: 680,
    speed: 0.75,
    attackDamage: 42,
    buildingDamage: 95,
    attackCooldown: 1.2,
    range: 0.9,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.45,
    peelChance: 0.65,
    deployRules: {
      placementType: 'backline',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0.4,
      canPlaceBehindEnemies: true,
    },
  },
  archer: {
    id: 'archer',
    name: 'Песчаный Стрелок',
    squadSize: 3,
    cost: 3,
    unitType: 'ground',
    armorClass: 'ranged',
    hp: 190,
    speed: 0.85,
    attackDamage: 19,
    airDamage: 15,
    buildingDamage: 9,
    attackCooldown: 1,
    range: 4.5,
    targetTypes: ['ground', 'air', 'building'],
    canBlockGround: true,
    turnDelay: 0.35,
    peelChance: 0.45,
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
  },
  spearman: {
    id: 'spearman',
    name: 'Пикейщик Каравана',
    squadSize: 3,
    cost: 3,
    unitType: 'ground',
    armorClass: 'antiHeavy',
    hp: 320,
    speed: 0.85,
    attackDamage: 35,
    buildingDamage: 18,
    attackCooldown: 0.9,
    range: 1.4,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.3,
    peelChance: 0.65,
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
  },
  drone: {
    id: 'drone',
    name: 'Дюнный Сокол',
    squadSize: 1,
    cost: 4,
    unitType: 'air',
    armorClass: 'light',
    hp: 280,
    speed: 1.1,
    attackDamage: 20,
    buildingDamage: 17,
    attackCooldown: 1,
    range: 2.8,
    targetTypes: ['ground', 'building'],
    canBlockGround: false,
    turnDelay: 0.2,
    peelChance: 0,
    deployRules: {
      placementType: 'backline',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0.5,
      canPlaceBehindEnemies: true,
    },
  },
  heavy: {
    id: 'heavy',
    name: 'Латник Пустыни',
    squadSize: 1,
    cost: 5,
    unitType: 'ground',
    armorClass: 'heavy',
    hp: 900,
    speed: 0.5,
    attackDamage: 60,
    buildingDamage: 45,
    attackCooldown: 1.5,
    range: 0.9,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.7,
    peelChance: 0,
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0.6,
      canPlaceBehindEnemies: true,
    },
  },
  guard: {
    id: 'guard',
    name: 'Гвардеец Чести',
    squadSize: 2,
    cost: 4,
    unitType: 'ground',
    armorClass: 'guard',
    hp: 680,
    speed: 0.6,
    attackDamage: 40,
    buildingDamage: 18,
    attackCooldown: 1.1,
    range: 0.9,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    factionOnly: 'honor',
    faction: 'house_honor',
    rarity: 'rare',
    turnDelay: 0.4,
    peelChance: 0.65,
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
  },

  // ── Магазинная волна v1.1 ─────────────────────────────────────────────────

  dune_guard: {
    name: 'Страж Бастиона',
    squadSize: 2,
    cost: 3,
    unitType: 'ground',
    armorClass: 'mediumControl',
    hp: 520,
    speed: 0.75,
    attackDamage: 32,
    buildingDamage: 12,
    attackCooldown: 1.1,
    range: 1.0,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.35,
    peelChance: 0.55,
    rarity: 'common',
    faction: 'universal',
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'first_hit_slow', slowPct: 0.25, duration: 2.0 },
  },

  sand_runner: {
    name: 'Песчаный Бегун',
    squadSize: 2,
    cost: 2,
    unitType: 'ground',
    armorClass: 'lightRaider',
    hp: 230,
    speed: 1.5,
    sprintSpeed: 2.1,
    attackDamage: 24,
    buildingDamage: 36,
    attackCooldown: 0.8,
    range: 0.8,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.15,
    peelChance: 0.60,
    rarity: 'common',
    faction: 'universal',
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'opening_sprint_building_hit', sprintDuration: 2.5, sprintSpeed: 2.1, firstBuildingHitMultiplier: 2 },
  },

  hook_thrower: {
    name: 'Метатель Крюков',
    squadSize: 1,
    cost: 3,
    unitType: 'ground',
    armorClass: 'rangedControl',
    hp: 240,
    speed: 0.85,
    attackDamage: 30,
    buildingDamage: 10,
    attackCooldown: 1.4,
    range: 3.2,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.35,
    peelChance: 0.30,
    rarity: 'common',
    faction: 'universal',
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'first_hit_hook', interruptDuration: 0.5, pullDistance: 0.45, excludedArmor: ['heavy', 'legendaryHonorDefender'], excludedUnitTypes: ['air'] },
  },

  caravan_shields: {
    name: 'Щитоносцы Каравана',
    squadSize: 3,
    cost: 4,
    unitType: 'ground',
    armorClass: 'shield',
    hp: 620,
    speed: 0.65,
    attackDamage: 34,
    buildingDamage: 20,
    attackCooldown: 1.0,
    range: 0.9,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.45,
    peelChance: 0.55,
    rarity: 'rare',
    faction: 'universal',
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'front_ranged_reduction', reductionPct: 0.30 },
  },

  rock_demolitionist: {
    name: 'Подрывник Скалы',
    squadSize: 1,
    cost: 4,
    unitType: 'ground',
    armorClass: 'explosive',
    hp: 260,
    speed: 0.70,
    attackDamage: 55,
    buildingDamage: 12,
    attackCooldown: 1.8,
    range: 2.5,
    aoeRadius: 1.2,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.40,
    peelChance: 0,
    rarity: 'rare',
    faction: 'universal',
    deployRules: {
      placementType: 'backline',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0.3,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'aoe_attack', radius: 1.2 },
  },

  caravan_duelist: {
    name: 'Дуэлянт Каравана',
    squadSize: 1,
    cost: 3,
    unitType: 'ground',
    armorClass: 'duelist',
    hp: 470,
    speed: 1.05,
    attackDamage: 48,
    buildingDamage: 16,
    attackCooldown: 1.0,
    range: 0.9,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.25,
    peelChance: 0,
    rarity: 'rare',
    faction: 'universal',
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'duel_bonus', isolatedRadius: 2.0, damageBonusPct: 0.25, incomingReductionPct: 0.15 },
  },

  desert_trapper: {
    name: 'Пустынный Ловец',
    squadSize: 2,
    cost: 4,
    unitType: 'ground',
    armorClass: 'trapper',
    hp: 380,
    speed: 0.90,
    attackDamage: 36,
    buildingDamage: 16,
    attackCooldown: 1.0,
    range: 1.2,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    turnDelay: 0.30,
    peelChance: 0.50,
    rarity: 'epic',
    faction: 'universal',
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'first_fast_enemy_root', radius: 3.0, rootDuration: 1.25, targetArmor: ['light', 'lightRaider'] },
  },

  siege_drone: {
    name: 'Дюнный Осадный Дрон',
    squadSize: 1,
    cost: 4,
    unitType: 'air',
    armorClass: 'siegeAir',
    hp: 320,
    speed: 1.05,
    attackDamage: 45,
    engineerDamage: 45,
    buildingDamage: 48,
    attackCooldown: 1.2,
    range: 3.4,
    targetTypes: ['engineer', 'building'],
    canBlockGround: false,
    turnDelay: 0.20,
    peelChance: 0,
    rarity: 'epic',
    faction: 'universal',
    deployRules: {
      placementType: 'backline',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0.5,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'siege_target_priority' },
  },

  garrison_marshal: {
    name: 'Маршал Гарнизона',
    squadSize: 1,
    cost: 6,
    unitType: 'ground',
    armorClass: 'legendaryHonorDefender',
    hp: 1050,
    speed: 0.55,
    attackDamage: 68,
    buildingDamage: 32,
    attackCooldown: 1.35,
    range: 1.0,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    factionOnly: 'honor',
    faction: 'house_honor',
    turnDelay: 0.65,
    peelChance: 0,
    rarity: 'legendary',
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0.6,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'garrison_counter', ownHalfReductionPct: 0.18, damageTakenForCounter: 250, counterDamageBonusPct: 0.60 },
  },

  oath_blade: {
    name: 'Клинок Присяги',
    squadSize: 1,
    cost: 6,
    unitType: 'ground',
    armorClass: 'legendaryHonorDuelist',
    hp: 820,
    speed: 0.85,
    attackDamage: 72,
    buildingDamage: 28,
    attackCooldown: 1.25,
    range: 1.0,
    targetTypes: ['ground', 'building'],
    canBlockGround: true,
    factionOnly: 'honor',
    faction: 'house_honor',
    turnDelay: 0.30,
    peelChance: 0,
    rarity: 'legendary',
    deployRules: {
      placementType: 'own_half',
      allowedLanes: ['left', 'center', 'right'],
      deployDelay: 0.4,
      canPlaceBehindEnemies: true,
    },
    special: { type: 'oath_mark', radius: 6.0, minTargetCost: 5, speedBonusPct: 0.20, firstHitFlatBonus: 45, expensiveTargetBonusPct: 0.25, microStun: 0.35 },
  },
};

// Returns the spice cost to play a card given the player's current engineer stage
// ? Engineer escalating cost — revisit during economy balancing
export function getCardCost(cardId, engineerStage = 0) {
  if (cardId === 'engineer') {
    return Math.min(2 + engineerStage, 4);
  }
  return CARD_DEFS[cardId].cost;
}

// Минимальное время (секунды от старта матча) для вызова инженера каждой стадии
// Стадия 1 — с любого момента, стадия 2 — после 1 мин, стадия 3 — после 2 мин
export const ENGINEER_MIN_TIMES = [0, 60, 120];

// Returns true if the card can be played given the current game state
export function canPlayCard(cardId, economy, elapsedSeconds = 0) {
  if (cardId === 'engineer') {
    if (economy.engineerStage >= 3) return false; // max stage reached
    const minTime = ENGINEER_MIN_TIMES[economy.engineerStage]; // indexed by current stage
    if (elapsedSeconds < minTime) return false; // too early for next engineer
  }
  return economy.canAfford(getCardCost(cardId, economy.engineerStage));
}

export const CARD_ICONS = {
  engineer:            '⚙',
  scout:               '⚡',
  swordsman:           '⚔',
  assault:             '🛡',
  archer:              '🏹',
  spearman:            '🔱',
  drone:               '✦',
  heavy:               '🪖',
  guard:               '⛨',
  // v1.1
  dune_guard:          '⛨',
  sand_runner:         '↯',
  hook_thrower:        '⚓',
  caravan_shields:     '◫',
  rock_demolitionist:  '✶',
  caravan_duelist:     '✙',
  desert_trapper:      '⌖',
  siege_drone:         '◈',
  garrison_marshal:    '♔',
  oath_blade:          '⚜',
};

// Card background colors (header tint)
export const CARD_COLORS = {
  engineer:            '#7a5a10',
  scout:               '#0a5a5a',
  swordsman:           '#0a2a6a',
  assault:             '#5a2a0a',
  archer:              '#0a4a1a',
  spearman:            '#2a4a1a',
  drone:               '#1a3060',
  heavy:               '#4a2a4a',
  guard:               '#5a3a00',
  // v1.1 — common: sandy, rare: copper-blue, epic: dark violet, legendary: deep gold
  dune_guard:          '#4a3a18',
  sand_runner:         '#3a4a18',
  hook_thrower:        '#1a3a3a',
  caravan_shields:     '#1a2a4a',
  rock_demolitionist:  '#3a1a0a',
  caravan_duelist:     '#2a1a3a',
  desert_trapper:      '#3a0a3a',
  siege_drone:         '#0a2040',
  garrison_marshal:    '#5a4a00',
  oath_blade:          '#4a3a00',
};

export const MAX_COPIES_PER_CARD = 3;
export const DECK_SIZE            = 10;

// Default AI deck for 1P mode (testing deck — covers all unit types)
export const AI_DECK = [
  'scout',
  'swordsman', 'swordsman',
  'assault', 'assault',
  'archer',
  'spearman',
  'drone',
  'heavy',
  'engineer',
];

// Test deck for v1.1 market wave — covers new units without breaking AI
export const AI_DECK_MARKET_TEST = [
  'sand_runner', 'sand_runner',
  'dune_guard',
  'swordsman',
  'assault',
  'rock_demolitionist',
  'desert_trapper',
  'siege_drone',
  'heavy',
  'engineer',
];

// Rarity display order and labels
export const RARITY_ORDER  = ['common', 'rare', 'epic', 'legendary'];
export const RARITY_LABELS = { common: 'Обычная', rare: 'Редкая', epic: 'Эпик', legendary: 'Легенда' };
export const RARITY_COLORS = { common: '#9a8878', rare: '#5599dd', epic: '#cc77ee', legendary: '#e8c030' };
